// Installing and inspecting the native messaging host.
//
// The host (native-host.js + transport.js, no dependencies) is copied into a
// fixed per-user folder and registered with every Chromium-based browser
// found. Copying, rather than pointing browsers at wherever this package
// lives, keeps the host working when the package runs from npx's cache. The
// MCP server calls ensureHost() on every start, so installing is automatic
// and stays repaired after updates; `browser-driver-mcp install-host` does
// the same thing explicitly.

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { HOST_NAME, EXTENSION_ID, VERSION } from "./transport.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const home = os.homedir();

export const SUPPORTED = process.platform === "darwin" || process.platform === "linux";

export const dataDir = process.platform === "darwin"
  ? path.join(home, "Library/Application Support/browser-driver-mcp")
  : path.join(home, ".local/share/browser-driver-mcp");
export const hostDir = path.join(dataDir, "host");
export const launcher = path.join(dataDir, "native-host");

const HOST_FILES = ["native-host.js", "transport.js"];

// Earlier versions of this project registered under other names.
const LEGACY_HOST_NAMES = ["com.github.darrinm.chrome_debug_bridge", "com.github.darrinm.better_browser_mcp"];
const LEGACY_DATA_DIRS = ["chrome-debug-bridge", "better-browser-mcp"].map((n) => path.join(path.dirname(dataDir), n));

// Browser profile roots, by display name. Only those that exist are used.
export function browserDirs() {
  const list = process.platform === "darwin"
    ? [
        ["Google Chrome", "Google/Chrome"], ["Google Chrome Beta", "Google/Chrome Beta"],
        ["Google Chrome Dev", "Google/Chrome Dev"], ["Google Chrome Canary", "Google/Chrome Canary"],
        ["Chromium", "Chromium"], ["Brave", "BraveSoftware/Brave-Browser"], ["Microsoft Edge", "Microsoft Edge"],
        ["Vivaldi", "Vivaldi"], ["Arc", "Arc/User Data"],
      ].map(([name, d]) => ({ name, dir: path.join(home, "Library/Application Support", d) }))
    : [
        ["Google Chrome", "google-chrome"], ["Google Chrome Beta", "google-chrome-beta"],
        ["Google Chrome Dev", "google-chrome-unstable"], ["Chromium", "chromium"],
        ["Brave", "BraveSoftware/Brave-Browser"], ["Microsoft Edge", "microsoft-edge"], ["Vivaldi", "vivaldi"],
      ].map(([name, d]) => ({ name, dir: path.join(home, ".config", d) }));
  return list.filter((b) => fs.existsSync(b.dir));
}

export function manifestPathFor(browserDir) {
  return path.join(browserDir, "NativeMessagingHosts", `${HOST_NAME}.json`);
}

// Chrome derives an extension's ID from the public key in its manifest's
// "key" field, or, for an unpacked extension without one, from the folder's
// path: the first 128 bits of SHA-256, written with the letters a-p.
function toId(bytes) {
  return crypto
    .createHash("sha256")
    .update(bytes)
    .digest("hex")
    .slice(0, 32)
    .replace(/./g, (c) => String.fromCharCode(97 + parseInt(c, 16)));
}

// The extension IDs allowed to launch the host: the published ID, plus the
// ID of ../extension when running from a checkout (the same, unless the
// checkout has no manifest key), plus any passed explicitly.
export function extensionIds(extra = []) {
  const ids = new Set([EXTENSION_ID, ...extra]);
  const manifestFile = path.resolve(here, "../extension/manifest.json");
  if (fs.existsSync(manifestFile)) {
    const { key } = JSON.parse(fs.readFileSync(manifestFile, "utf8"));
    ids.add(key ? toId(Buffer.from(key, "base64")) : toId(path.dirname(manifestFile)));
  }
  return [...ids];
}

// Browsers launch hosts with a minimal PATH, so the launcher names node by
// absolute path. Prefer the first node on PATH (e.g. a stable Homebrew
// symlink) over process.execPath, which may be a versioned path.
export function findNode() {
  for (const dir of (process.env.PATH || "").split(path.delimiter)) {
    const candidate = path.join(dir, "node");
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      return candidate;
    } catch {}
  }
  return process.execPath;
}

function launcherScript(node) {
  return "#!/bin/sh\n" +
    "# Launched by the browser via native messaging. Generated by browser-driver-mcp.\n" +
    `exec "${node}" "${path.join(hostDir, "native-host.js")}" "$@"\n`;
}

function hostManifest(ids) {
  return JSON.stringify({
    name: HOST_NAME,
    description: "Browser Driver MCP native host",
    path: launcher,
    type: "stdio",
    allowed_origins: ids.map((id) => `chrome-extension://${id}/`),
  }, null, 2) + "\n";
}

// Write a file only if its content differs; returns whether it changed.
function writeIfChanged(file, content, mode) {
  try {
    if (fs.readFileSync(file, "utf8") === content) {
      if (mode !== undefined) fs.chmodSync(file, mode);
      return false;
    }
  } catch {}
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, mode !== undefined ? { mode } : undefined);
  if (mode !== undefined) fs.chmodSync(file, mode);
  return true;
}

// Install or repair the host. Idempotent; returns the list of changes made.
export function ensureHost({ extraIds = [] } = {}) {
  if (!SUPPORTED) throw new Error("Native host installation is only automated on macOS and Linux.");
  const changes = [];

  for (const { dir } of browserDirs()) {
    for (const name of LEGACY_HOST_NAMES) {
      const file = path.join(dir, "NativeMessagingHosts", `${name}.json`);
      if (fs.existsSync(file)) {
        fs.unlinkSync(file);
        changes.push(`removed legacy ${file}`);
      }
    }
  }
  for (const dir of LEGACY_DATA_DIRS) {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
      changes.push(`removed legacy ${dir}`);
    }
  }

  for (const file of HOST_FILES) {
    if (writeIfChanged(path.join(hostDir, file), fs.readFileSync(path.join(here, file), "utf8"))) {
      changes.push(`copied ${file} to ${hostDir}`);
    }
  }
  // The copied files are ES modules and read the version from here.
  if (writeIfChanged(path.join(hostDir, "package.json"), JSON.stringify({ type: "module", version: VERSION }, null, 2) + "\n")) {
    changes.push(`wrote ${path.join(hostDir, "package.json")}`);
  }
  if (writeIfChanged(launcher, launcherScript(findNode()), 0o755)) changes.push(`wrote launcher ${launcher}`);

  const manifest = hostManifest(extensionIds(extraIds));
  for (const { name, dir } of browserDirs()) {
    if (writeIfChanged(manifestPathFor(dir), manifest)) changes.push(`registered with ${name}`);
  }
  return changes;
}

export function uninstallHost() {
  const changes = [];
  for (const { dir } of browserDirs()) {
    for (const name of [HOST_NAME, ...LEGACY_HOST_NAMES]) {
      const file = path.join(dir, "NativeMessagingHosts", `${name}.json`);
      if (fs.existsSync(file)) {
        fs.unlinkSync(file);
        changes.push(`removed ${file}`);
      }
    }
  }
  for (const dir of [dataDir, ...LEGACY_DATA_DIRS]) {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
      changes.push(`removed ${dir}`);
    }
  }
  return changes;
}

// Find which browser profiles have the extension installed, by reading each
// profile's preferences. Best effort: the files can lag the live browser.
export function findExtensionInstalls() {
  const ids = new Set(extensionIds());
  const found = [];
  for (const { name, dir } of browserDirs()) {
    let profiles = [];
    try {
      profiles = fs.readdirSync(dir).filter((p) => p === "Default" || /^Profile \d+$/.test(p));
    } catch {}
    for (const profile of profiles) {
      for (const prefsFile of ["Secure Preferences", "Preferences"]) {
        let settings;
        try {
          settings = JSON.parse(fs.readFileSync(path.join(dir, profile, prefsFile), "utf8"))?.extensions?.settings;
        } catch {
          continue;
        }
        for (const id of ids) {
          const s = settings && settings[id];
          if (s && !found.some((f) => f.browser === name && f.profile === profile)) {
            found.push({ browser: name, profile, id, enabled: !s.disable_reasons || !s.disable_reasons.length, path: s.path });
          }
        }
      }
    }
  }
  return found;
}
